version: '3.8'
services:
  db:
    image: postgres:15
    container_name: escolar_pg_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_gestao_escolar
    ports:
      - "5433:5432"